[theme]
base = "dark"
primaryColor = "#6366F1"
backgroundColor = "#090d16"
secondaryBackgroundColor = "#151b2d"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
